Java distribution option
3arthqu4ke/mc-runtime-test pull request #6
Opened 2024-04-09 13:56 UTC by Ai2473

2024-04-09 17:27 UTC, 3arthqu4ke requested changes

2024-04-09 17:27 UTC, 3arthqu4ke commented on README.md
Could you document the option to set a distribution here?

2024-04-09 20:53 UTC, Ai2473 commented on README.md
Is it good like this?

2024-04-10 20:59 UTC, 3arthqu4ke approved these changes

2024-04-10 21:00 UTC, merged

2024-04-10 21:00 UTC, 3arthqu4ke commented
Awesome!